export const PERMISSIONS = Object.freeze({
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  ROLE_CREATE: 'role:create',
  ROLE_READ: 'role:read',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',
  REPORT_READ: 'report:read',
  // Invoicing domain — authority/permission-based, centralized here so no
  // UI component ever hardcodes a permission string.
  INVOICE_CREATE: 'invoice:create',
  INVOICE_READ: 'invoice:read',
  INVOICE_UPDATE: 'invoice:update',
  INVOICE_DELETE: 'invoice:delete',

  PREFIX_VIEW: 'prefix:view',
  PREFIX_CREATE: 'prefix:create',
  PREFIX_UPDATE: 'prefix:update',
  PREFIX_DELETE: 'prefix:delete',

  SUFFIX_VIEW: 'suffix:view',
  SUFFIX_CREATE: 'suffix:create',
  SUFFIX_UPDATE: 'suffix:update',
  SUFFIX_DELETE: 'suffix:delete',

  DOCUMENT_TYPE_VIEW: 'document_type:view',

  CUSTOM_HEADER_VIEW: 'custom_header:view',
  CUSTOM_HEADER_CREATE: 'custom_header:create',
  CUSTOM_HEADER_UPDATE: 'custom_header:update',
  CUSTOM_HEADER_DELETE: 'custom_header:delete',
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_READ: 'customer:read',
  CUSTOMER_UPDATE: 'customer:update',
  PRODUCT_CREATE: 'product:create',
  PRODUCT_READ: 'product:read',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_DELETE: 'product:delete',
  VENDOR_CREATE: 'vendor:create',
  VENDOR_READ: 'vendor:read',
  VENDOR_UPDATE: 'vendor:update',
  VENDOR_DELETE: 'vendor:delete',
  SETUP_WIZARD: 'setup:wizard',
});
